# Generated by Django 4.1.1 on 2022-09-18 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flights', '0002_onlinepassenger_stationpassenger_delete_passenger'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('flights', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_passengers', to='flights.flight')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='StationPassenger',
            new_name='StationBooking',
        ),
        migrations.DeleteModel(
            name='OnlinePassenger',
        ),
    ]
