# Generated by Django 4.1.1 on 2022-09-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_onlinebooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinebooking',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
