# Generated by Django 4.1.1 on 2022-09-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_onlinebooking_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(unique=True)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='time',
            field=models.ManyToManyField(related_name='time_date', to='flights.time'),
        ),
    ]
